import { createHash } from 'crypto';
import { readFile, writeFile, readdir, mkdir, copyFile } from 'fs/promises';
import { join, basename } from 'path';
import { fileURLToPath } from 'url';

const __dirname = fileURLToPath(new URL('..', import.meta.url));
const outDir = join(__dirname, 'public', 'vendor');

const vendored = [
  {
    name: 'xlsx.full.min.js',
    source: join(__dirname, 'node_modules', 'xlsx', 'dist', 'xlsx.full.min.js'),
    pkg: 'xlsx',
    license: 'Apache-2.0',
    url: 'https://sheetjs.com/'
  },
  {
    name: 'chart.umd.min.js',
    source: join(__dirname, 'node_modules', 'chart.js', 'dist', 'chart.umd.min.js'),
    pkg: 'chart.js',
    license: 'MIT',
    url: 'https://www.chartjs.org/'
  }
];

const lucideIcons = [
  'house',
  'user',
  'users',
  'layout-dashboard',
  'database',
  'upload',
  'shield-check',
  'file-spreadsheet',
  'clipboard-plus',
  'circle-alert',
  'circle-check',
  'circle-x',
  'menu',
  'chevron-right',
  'activity',
  'lock'
];

async function sha256(path) {
  const data = await readFile(path);
  return createHash('sha256').update(data).digest('hex');
}

async function buildLucideSprite() {
  const iconDir = join(__dirname, 'node_modules', 'lucide-static', 'icons');
  const symbols = [];
  for (const name of lucideIcons) {
    const path = join(iconDir, `${name}.svg`);
    try {
      let svg = await readFile(path, 'utf8');
      // Strip root svg tag, keep inner contents and add symbol wrapper.
      svg = svg.replace(/<svg[^>]*>/i, '').replace(/<\/svg>/i, '');
      symbols.push(`  <symbol id="${name}" viewBox="0 0 24 24">\n    ${svg.trim()}\n  </symbol>`);
    } catch (err) {
      console.warn(`Missing Lucide icon: ${name}`);
    }
  }
  const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none;" aria-hidden="true">\n  <defs>\n${symbols.join('\n')}\n  </defs>\n</svg>`;
  const spritePath = join(outDir, 'lucide-sprite.svg');
  await writeFile(spritePath, sprite);
  return spritePath;
}

async function main() {
  await mkdir(outDir, { recursive: true });
  const records = [];

  for (const item of vendored) {
    await copyFile(item.source, join(outDir, item.name));
    const hash = await sha256(join(outDir, item.name));
    const pkgJson = JSON.parse(await readFile(join(__dirname, 'node_modules', item.pkg, 'package.json'), 'utf8'));
    records.push({ ...item, version: pkgJson.version, hash });
  }

  const spritePath = await buildLucideSprite();
  const lucidePkg = JSON.parse(await readFile(join(__dirname, 'node_modules', 'lucide-static', 'package.json'), 'utf8'));
  records.push({
    name: 'lucide-sprite.svg',
    pkg: 'lucide-static',
    version: lucidePkg.version,
    license: 'ISC',
    url: 'https://lucide.dev/',
    hash: await sha256(spritePath)
  });

  const lines = [
    '# Third-party vendored dependencies',
    '',
    'All runtime dependencies are bundled locally so the hub works offline and without CDN.',
    '',
    '| File | Package | Version | License | Source | SHA-256 |',
    '|------|---------|---------|---------|--------|---------|'
  ];
  for (const r of records) {
    lines.push(`| ${r.name} | ${r.pkg} | ${r.version} | ${r.license} | ${r.url} | \`${r.hash}\` |`);
  }
  lines.push('');
  lines.push('Generated by `npm run vendor`.');
  lines.push('');

  await writeFile(join(outDir, 'THIRD_PARTY.md'), lines.join('\n'));
  console.log(`Vendored ${records.length} files to ${outDir}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
